version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: debezium/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_CONNECT: zookeeper:2181
